config/routes.rb
Rails.application.routes.draw do
	resources :users, except: [:new]
  	resources :articles
  	#get 'pages/about'
	root 'pages#home'
	get 'about', to: 'pages#about'
	get 'signup', to: 'users#new'
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
	resources :categories, except: [:destroy]
end

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'ALPHA BLOG', 
      root_path, class:"navbar-brand" 
  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Us",
          about_path, class:"nav-link"
        %>
      </li>
      <li class="nav-item">
      <%= link_to "Bloggers",
        users_path, class:"nav-link"
      %>
    </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
         <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
        <% end %> 
         <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if logged_in? && current_user.admin? %>
       <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
      <% end %> 
       <%= link_to "View categories", categories_path, class: "dropdown-item" %>
      </div>
    </li>

    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to "View your profile",user_path(current_user), class: "dropdown-item" %>
         <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
         <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Logout",
        logout_path, class:"nav-link", method: :delete
        %>
      </li>
    <%else %>
      <li class="nav-item">
        <%= link_to "Log in",
          login_path, class:"nav-link"
        %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up",
          signup_path, class:"nav-link"
        %>
      </li>
    <% end %>

    </ul>
  </div>
</nav>

app/views/pages/about.html.erb
<div class="container mt-4" id ="home-container">
	<div class="jumbotron text-center text-white" >
		 <h1 class="display-4 ">Welcome to the About page</h1>
		 <p class="lead">Here is about the Bloggers who want to write articles.</p>
		 <hr class="my-4">
		 <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		   <%= link_to "Home", root_path, class: "btn btn-outline-dark btn-lg text-white"  %>
	</div>
</div>

app/views/pages/home.html.erb
<div class="container mt-4" id ="home-container">
	<div class="jumbotron text-center text-white" >
		 <h1 class="display-4 ">Alpha Blog </h1>
		 <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		 <hr class="my-4">
		 <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		   <%= link_to "Sign up!", signup_path, class: "btn btn-outline-dark btn-lg text-white"  %>
	</div>
</div>


	